import React from "react"
import { Spinner } from "@utilitywarehouse/native-ui"
import figma from "@figma/code-connect"
import { colors, colorsDark } from "@utilitywarehouse/colour-system"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Spinner,
  "https://www.figma.com/file/3RY3OvLA88yZksRjOfjQJm/UW-App-UI?type=design&node-id=5627-2858&mode=dev",
  {
    props: {
      size: figma.enum("size", {
        "x-small": "xs",
        small: "sm",
        medium: "md",
        large: "lg",
      }),
      theme: figma.enum("theme", {
        light: "light",
        dark: "dark",
      }),
    },
    example: ({size, theme}) => <Spinner size={size} color={theme === 'light' ? colors.purple800 : colorsDark.purple800} />,
  },
)
