import React from "react"
import { Link } from "./Link"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Link,
  "https://www.figma.com/design/4FFYTLWJ2hQpj36JplQQUw/UW-Web-UI?node-id=5803-26758&m=dev",
  {
    props: {
      iconRight: figma.instance("Icon Right"),
      iconLeft: figma.instance("Icon Left"),
      iconLeft: figma.boolean("Icon Left?"),
      iconRight: figma.boolean("Icon Right?"),
      text: figma.string("Text"),
      state: figma.enum("state", {
        default: "default",
        hover: "hover",
        active: "active",
        focus: "focus",
        disabled: "disabled",
      }),
      size: figma.enum("size", {
        "large - 24": "large---24",
        "small - 16": "small---16",
      }),
      inverted: figma.boolean("inverted"),
    },
    example: (props) => <Link />,
  },
)
