export {
  createMuiTheme,
  unstable_createMuiStrictModeTheme,
  adaptV4Theme,
  createStyles,
  makeStyles,
  responsiveFontSizes,
  duration,
  easing,
  useTheme,
  unstable_useThemeProps,
  withStyles,
  withTheme,
  experimentalStyled,
  styled,
  MuiThemeProvider,
  createGenerateClassName,
  jssPreset,
} from "@material-ui/core/styles";

export type {
  Breakpoint,
  BreakpointOverrides,
  DeprecatedThemeOptions,
  Direction,
  Palette,
  PaletteColor,
  PaletteColorOptions,
  PaletteOptions,
  SimplePaletteColorOptions,
  ComponentsPropsList,
  Duration,
  Easing,
  ThemeOptions,
  Theme,
  ThemeProviderProps as MuiThemeProviderProps,
  Transitions,
  TransitionsOptions,
  TypographyStyle,
  TypographyVariant,
  TypographyVariants,
  TypographyVariantsOptions,
  WithStyles,
  WithTheme,
  Styles,
  StyleRules,
  StyleRulesCallback,
  StyledComponentProps,
  CreateMUIStyled,
  ComponentCreator,
  StyledProps,
  ServerStyleSheets,
  StylesProvider,
  ComponentsProps,
  ComponentsVariants,
  ComponentsOverrides,
} from "@material-ui/core/styles";

export * from "@material-ui/core/styles/colorManipulator";
export * from "@material-ui/core/styles/useThemeProps";
