import React from 'react';
import { Input } from './';
import figma from '@figma/code-connect';
import { EyeMediumIcon } from '@utilitywarehouse/react-native-icons';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Input,
  'https://www.figma.com/design/3RY3OvLA88yZksRjOfjQJm/UW-App-UI?node-id=6990-3022&m=dev',
  {
    props: {
      state: figma.enum('state', {
        initial: 'initial',
        focus: 'focus',
        filled: 'filled',
      }),
      placeholder: figma.boolean('placeholder', {
        true: figma.nestedProps('.Parts/Input value', {
          text: figma.string('Text'),
        }),
        false: { text: undefined },
      }),
      validationStatus: figma.enum('validationStatus', {
        initial: undefined,
        invalid: 'invalid',
        valid: 'valid',
      }),
      disabled: figma.boolean('disabled'),
      readOnly: figma.boolean('readOnly'),
      iconLeft: figma.boolean('Icon Left?', {
        true: figma.nestedProps('.Parts/Content Left', {
          icon: figma.instance('Icon'),
        }),
        false: {
          icon: undefined,
        },
      }),
      value: figma.nestedProps('.Parts/Input value', {
        text: figma.boolean('placeholder', {
          true: undefined,
          false: figma.string('Text'),
        }),
      }),
    },
    example: props => (
      <Input
        validationStatus={props.validationStatus}
        placeholder={props.placeholder.text}
        readonly={props.readOnly}
        value={props.value.text}
        disabled={props.disabled}
        leadingIcon={props.iconLeft.icon}
      />
    ),
  }
);

// Password Input
figma.connect(
  Input,
  'https://www.figma.com/design/3RY3OvLA88yZksRjOfjQJm/UW-App-UI?node-id=7928-5958&m=dev',
  {
    props: {
      state: figma.enum('state', {
        initial: 'initial',
        focus: 'focus',
        filled: 'filled',
      }),
      placeholder: figma.boolean('placeholder', {
        true: figma.nestedProps('.Parts/Input value', {
          text: figma.string('Text'),
        }),
        false: { text: undefined },
      }),
      validationStatus: figma.enum('validationStatus', {
        initial: undefined,
        invalid: 'invalid',
        valid: 'valid',
      }),
      disabled: figma.boolean('disabled'),
      readOnly: figma.boolean('readOnly'),
      iconLeft: figma.boolean('Icon Left?', {
        true: figma.nestedProps('.Parts/Content Left', {
          icon: figma.instance('Icon'),
        }),
        false: {
          icon: undefined,
        },
      }),
      value: figma.nestedProps('.Parts/Input value', {
        text: figma.boolean('placeholder', {
          true: undefined,
          false: figma.string('Text'),
        }),
      }),
    },
    example: props => (
      <Input
        validationStatus={props.validationStatus}
        placeholder={props.placeholder.text}
        readonly={props.readOnly}
        value={props.value.text}
        disabled={props.disabled}
        leadingIcon={props.iconLeft.icon}
        trailingIcon={EyeMediumIcon}
      />
    ),
  }
);
