import { colorsDark, colors, colorsCommon } from '@utilitywarehouse/colour-system';
import { DimensionValue, Platform, TextStyle } from 'react-native';
import { breakpoints } from './breakpoints';
import { components } from '@utilitywarehouse/design-tokens';

const shared = {
  platform: Platform.OS,
  space: {
    px: '1px',
    '0': 0,
    '0.5': 2,
    '1': 4,
    '1.5': 6,
    '2': 8,
    '2.5': 10,
    '3': 12,
    '3.5': 14,
    '4': 16,
    '4.5': 18,
    '5': 20,
    '6': 24,
    '7': 28,
    '8': 32,
    '9': 36,
    '10': 40,
    '11': 44,
    '12': 48,
    '14': 56,
    '16': 64,
    '20': 80,
    '24': 96,
    '32': 128,
    '40': 160,
    '48': 192,
    '56': 224,
    '64': 256,
    '72': 288,
    '80': 320,
    '96': 384,
    '1/2': '50%',
    '1/3': '33.333%',
    '2/3': '66.666%',
    '1/4': '25%',
    '2/4': '50%',
    '3/4': '75%',
    '1/5': '20%',
    '2/5': '40%',
    '3/5': '60%',
    '4/5': '80%',
    '1/6': '16.666%',
    '2/6': '33.333%',
    '3/6': '50%',
    '4/6': '66.666%',
    '5/6': '83.333%',
    full: '100%' as DimensionValue,
  },
  borderWidths: {
    '0': 0,
    '1': 1,
    '2': 2,
    '4': 4,
    '8': 8,
  },
  radii: {
    none: 0,
    xs: 2,
    sm: 4,
    md: 6,
    lg: 8,
    xl: 12,
    '2xl': 16,
    '3xl': 24,
    '4xl': 32,
    full: 9999,
  },
  breakpoints,
  letterSpacings: {
    xs: -0.4,
    sm: -0.2,
    md: 0,
    lg: 0.2,
    xl: 0.4,
    '2xl': 1.6,
  },
  lineHeights: {
    '2xs': 16,
    xs: 18,
    sm: 20,
    md: 22,
    lg: 24,
    xl: 28,
    '2xl': 32,
    '3xl': 40,
    '4xl': 48,
    '5xl': 56,
    '6xl': 72,
    '7xl': 90,
  },
  fontWeights: {
    thin: '100' as TextStyle['fontWeight'],
    extralight: '200' as TextStyle['fontWeight'],
    light: '300' as TextStyle['fontWeight'],
    normal: '400' as TextStyle['fontWeight'],
    medium: '500' as TextStyle['fontWeight'],
    semibold: '600' as TextStyle['fontWeight'],
    bold: '700' as TextStyle['fontWeight'],
    extrabold: '800' as TextStyle['fontWeight'],
    black: '900' as TextStyle['fontWeight'],
  },
  fonts: {
    heading: 'Aeonik',
    body: 'Work Sans',
    mono: undefined,
  },
  fontSizes: {
    '2xs': 10,
    xs: 12,
    sm: 14,
    md: 16,
    lg: 18,
    xl: 20,
    '2xl': 24,
    '3xl': 28,
    '4xl': 32,
    '5xl': 36,
    '6xl': 40,
    '7xl': 48,
    '8xl': 56,
    '9xl': 64,
  },
  opacity: {
    0: 0,
    5: 0.05,
    10: 0.1,
    20: 0.2,
    25: 0.25,
    30: 0.3,
    40: 0.4,
    50: 0.5,
    60: 0.6,
    70: 0.7,
    75: 0.75,
    80: 0.8,
    90: 0.9,
    95: 0.95,
    100: 1,
  },
  globalStyle: {
    variants: {
      hardShadow: {
        '1': {
          shadowColor: colors.grey900,
          shadowOffset: {
            width: -2,
            height: 2,
          },
          shadowRadius: 8,
          shadowOpacity: 0.5,
          elevation: 10,
        },
        '2': {
          shadowColor: colors.grey900,
          shadowOffset: {
            width: 0,
            height: 3,
          },
          shadowRadius: 8,
          shadowOpacity: 0.5,
          elevation: 10,
        },
        '3': {
          shadowColor: colors.grey900,
          shadowOffset: {
            width: 2,
            height: 2,
          },
          shadowRadius: 8,
          shadowOpacity: 0.5,
          elevation: 10,
        },
        '4': {
          shadowColor: colors.grey900,
          shadowOffset: {
            width: 0,
            height: -3,
          },
          shadowRadius: 8,
          shadowOpacity: 0.5,
          elevation: 10,
        },
        '5': {
          shadowColor: colors.grey900,
          shadowOffset: {
            width: 0,
            height: 3,
          },
          shadowRadius: 8,
          shadowOpacity: 0.2,
          elevation: 10,
        },
      },
      softShadow: {
        '1': {
          shadowColor: colors.grey900,
          shadowOffset: {
            width: 0,
            height: 0,
          },
          shadowRadius: 10,
          shadowOpacity: 0.1,
          _android: {
            shadowColor: colors.grey900,
            elevation: 5,
            shadowOpacity: 0.05,
          },
        },
        '2': {
          shadowColor: colors.grey900,
          shadowOffset: {
            width: 0,
            height: 0,
          },
          shadowRadius: 20,
          elevation: 3,
          shadowOpacity: 0.1,
          _android: {
            shadowColor: colors.grey900,
            elevation: 10,
            shadowOpacity: 0.1,
          },
        },
        '3': {
          shadowColor: colors.grey900,
          shadowOffset: {
            width: 0,
            height: 0,
          },
          shadowRadius: 30,
          shadowOpacity: 0.1,
          elevation: 4,
          _android: {
            shadowColor: colors.grey900,
            elevation: 15,
            shadowOpacity: 0.15,
          },
        },
        '4': {
          shadowColor: colors.grey900,
          shadowOffset: {
            width: 0,
            height: 0,
          },
          shadowRadius: 40,
          shadowOpacity: 0.1,
          elevation: 10,
          _android: {
            shadowColor: colors.grey900,
            elevation: 20,
            shadowOpacity: 0.2,
          },
        },
      },
    },
  },
};

export const lightTheme = {
  colorMode: 'light',
  isLight: true,
  isDark: false,
  colors: {
    ...colors,
    ...colorsCommon,
    white: '#ffffff',
    black: '#000000',
  },
  tokens: {
    ...components.light,
  },
  ...shared,
};

export const darkTheme = {
  colorMode: 'dark',
  isLight: false,
  isDark: true,
  colors: {
    ...colorsDark,
    ...colorsCommon,
    white: '#ffffff',
    black: '#000000',
  },
  tokens: {
    ...components.dark,
  },
  ...shared,
};

export const themes = {
  light: lightTheme,
  dark: darkTheme,
};
