export const dataAttributes = {
  legacy: 'legacy-cwui',
  primary: 'primary',
  secondary: 'secondary',
  success: 'success',
  error: 'error',
  variant: 'variant',
  size: 'size',
  inverse: 'inverse-background',
  multiline: 'multiline',
  heading: 'heading',
  bgcolorBrand: 'bg-color-brand',
  bold: 'bold',
  noWrap: 'no-wrap',
};
