import React from 'react';
import { CheckboxIndicator, Checkbox } from '@utilitywarehouse/native-ui';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  CheckboxIndicator,
  'https://www.figma.com/design/3RY3OvLA88yZksRjOfjQJm/UW-App-UI?node-id=4454-3759&m=dev',
  {
    props: {
      checked: figma.boolean('checked'),
      state: figma.enum('state', {
        initial: 'initial',
        pressed: 'pressed',
      }),
      isDisabled: figma.boolean('isDisabled'),
      theme: figma.enum('theme', {
        light: 'light',
        dark: 'dark',
      }),
    },
    example: ({ checked, isDisabled }) => (
      <Checkbox
        value="some value"
        isChecked={checked}
        isDisabled={isDisabled}
        onChange={() => console.log('checkbox chacked')}
      >
        <CheckboxIndicator />
      </Checkbox>
    ),
  }
);
