import React from 'react';
import { Checkbox } from '@utilitywarehouse/native-ui';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Checkbox,
  'https://www.figma.com/design/3RY3OvLA88yZksRjOfjQJm/UW-App-UI?node-id=5623-561&m=dev',
  {
    props: {
      helperText562312: figma.boolean('Helper Text?'),
      isDisabled: figma.boolean('isDisabled'),
      theme: figma.enum('theme', {
        light: 'light',
        dark: 'dark',
      }),
      invalid: figma.boolean('invalid'),
    },
    example: props => <Checkbox />,
  }
);
