import type { ViewProps, ViewStyle } from 'react-native';
import type {
  BordeWidthValue,
  ColorValue,
  OpacityValue,
  RadiiValue,
  SpaceValue,
} from '../../types';

interface BoxProps
  extends Omit<
      ViewStyle,
      | 'padding'
      | 'paddingHorizontal'
      | 'paddingVertical'
      | 'paddingTop'
      | 'paddingBottom'
      | 'paddingLeft'
      | 'paddingRight'
      | 'paddingEnd'
      | 'paddingStart'
      | 'margin'
      | 'marginHorizontal'
      | 'marginVertical'
      | 'marginTop'
      | 'marginBottom'
      | 'marginLeft'
      | 'marginRight'
      | 'marginEnd'
      | 'marginStart'
      | 'columnGap'
      | 'gap'
      | 'rowGap'
      | 'backgroundColor'
      | 'borderColor'
      | 'borderBottomColor'
      | 'borderLeftColor'
      | 'borderRightColor'
      | 'borderTopColor'
      | 'borderBlockColor'
      | 'borderBlockEndColor'
      | 'borderBlockStartColor'
      | 'borderEndColor'
      | 'borderStartColor'
      | 'shadowColor'
      | 'borderRadius'
      | 'rounded'
      | 'borderBottomEndRadius'
      | 'borderBottomLeftRadius'
      | 'borderBottomRightRadius'
      | 'borderBottomStartRadius'
      | 'borderTopEndRadius'
      | 'borderTopLeftRadius'
      | 'borderTopRightRadius'
      | 'borderTopStartRadius'
      | 'borderEndEndRadius'
      | 'borderEndStartRadius'
      | 'borderStartEndRadius'
      | 'borderStartStartRadius'
      | 'opacity'
      | 'borderBottomWidth'
      | 'borderEndWidth'
      | 'borderLeftWidth'
      | 'borderRightWidth'
      | 'borderStartWidth'
      | 'borderTopWidth'
      | 'borderWidth'
      | 'height'
      | 'width'
      | 'maxWidth'
      | 'maxHeight'
    >,
    ViewProps {
  bg?: ColorValue;
  bgColor?: ColorValue;
  h?: SpaceValue;
  w?: SpaceValue;
  p?: SpaceValue;
  px?: SpaceValue;
  py?: SpaceValue;
  pt?: SpaceValue;
  pb?: SpaceValue;
  pr?: SpaceValue;
  pl?: SpaceValue;
  m?: SpaceValue;
  mx?: SpaceValue;
  my?: SpaceValue;
  mt?: SpaceValue;
  mb?: SpaceValue;
  mr?: SpaceValue;
  ml?: SpaceValue;
  rounded?: RadiiValue;
  padding?: SpaceValue;
  paddingHorizontal?: SpaceValue;
  paddingVertical?: SpaceValue;
  paddingTop?: SpaceValue;
  paddingBottom?: SpaceValue;
  paddingLeft?: SpaceValue;
  paddingRight?: SpaceValue;
  paddingEnd?: SpaceValue;
  paddingStart?: SpaceValue;
  margin?: SpaceValue;
  marginHorizontal?: SpaceValue;
  marginVertical?: SpaceValue;
  marginTop?: SpaceValue;
  marginBottom?: SpaceValue;
  marginLeft?: SpaceValue;
  marginRight?: SpaceValue;
  marginEnd?: SpaceValue;
  marginStart?: SpaceValue;
  columnGap?: SpaceValue;
  gap?: SpaceValue;
  rowGap?: SpaceValue;
  backgroundColor?: ColorValue;
  borderColor?: ColorValue;
  borderBottomColor?: ColorValue;
  borderLeftColor?: ColorValue;
  borderRightColor?: ColorValue;
  borderTopColor?: ColorValue;
  borderBlockColor?: ColorValue;
  borderBlockEndColor?: ColorValue;
  borderBlockStartColor?: ColorValue;
  borderEndColor?: ColorValue;
  borderStartColor?: ColorValue;
  shadowColor?: ColorValue;
  borderRadius?: RadiiValue;
  borderBottomEndRadius?: RadiiValue;
  borderBottomLeftRadius?: RadiiValue;
  borderBottomRightRadius?: RadiiValue;
  borderBottomStartRadius?: RadiiValue;
  borderTopEndRadius?: RadiiValue;
  borderTopLeftRadius?: RadiiValue;
  borderTopRightRadius?: RadiiValue;
  borderTopStartRadius?: RadiiValue;
  borderEndEndRadius?: RadiiValue;
  borderEndStartRadius?: RadiiValue;
  borderStartEndRadius?: RadiiValue;
  borderStartStartRadius?: RadiiValue;
  opacity?: OpacityValue;
  borderBottomWidth?: BordeWidthValue;
  borderEndWidth?: BordeWidthValue;
  borderLeftWidth?: BordeWidthValue;
  borderRightWidth?: BordeWidthValue;
  borderStartWidth?: BordeWidthValue;
  borderTopWidth?: BordeWidthValue;
  borderWidth?: BordeWidthValue;
  height?: SpaceValue;
  width?: SpaceValue;
  maxWidth?: SpaceValue;
  maxHeight?: SpaceValue;
}

export default BoxProps;
