/* eslint-disable @typescript-eslint/no-unsafe-assignment */
/* eslint-disable @typescript-eslint/no-unsafe-return */
/* eslint-disable react-hooks/exhaustive-deps */
import React, { memo, useMemo } from 'react';
import { View } from 'react-native';
import { createStyleSheet, useStyles } from 'react-native-unistyles';
import type BoxProps from './Box.props';
import getStyleValue from '../../utils/getStyleValue';

const Box: React.FC<BoxProps> = ({
  alignContent,
  alignItems,
  alignSelf,
  aspectRatio,
  borderBottomWidth,
  borderEndWidth,
  borderLeftWidth,
  borderRightWidth,
  borderStartWidth,
  borderTopWidth,
  borderWidth,
  bottom,
  display,
  end,
  flex,
  flexBasis,
  flexDirection,
  rowGap,
  gap,
  columnGap,
  flexGrow,
  flexShrink,
  flexWrap,
  height,
  justifyContent,
  left,
  margin,
  marginBottom,
  marginEnd,
  marginHorizontal,
  marginLeft,
  marginRight,
  marginStart,
  marginTop,
  marginVertical,
  maxHeight,
  maxWidth,
  minHeight,
  minWidth,
  overflow,
  padding,
  paddingBottom,
  paddingEnd,
  paddingHorizontal,
  paddingLeft,
  paddingRight,
  paddingStart,
  paddingTop,
  paddingVertical,
  position,
  right,
  start,
  top,
  width,
  zIndex,
  direction,
  backfaceVisibility,
  backgroundColor,
  borderBlockColor,
  borderBlockEndColor,
  borderBlockStartColor,
  borderBottomColor,
  borderBottomEndRadius,
  borderBottomLeftRadius,
  borderBottomRightRadius,
  borderBottomStartRadius,
  borderColor,
  borderCurve,
  borderEndColor,
  borderEndEndRadius,
  borderEndStartRadius,
  borderLeftColor,
  borderRadius,
  borderRightColor,
  borderStartColor,
  borderStartEndRadius,
  borderStartStartRadius,
  borderStyle,
  borderTopColor,
  borderTopEndRadius,
  borderTopLeftRadius,
  borderTopRightRadius,
  borderTopStartRadius,
  opacity,
  elevation,
  pointerEvents,
  cursor,
  shadowColor,
  shadowOffset,
  shadowOpacity,
  shadowRadius,
  transform,
  transformOrigin,
  bg,
  bgColor,
  h,
  w,
  p,
  px,
  py,
  pt,
  pb,
  pr,
  pl,
  m,
  mx,
  my,
  mt,
  mb,
  mr,
  ml,
  rounded,
  style,
  ...props
}) => {
  const {
    styles,
    theme: { space, colors, radii, borderWidths, opacity: themeOpacity },
  } = useStyles(stylesheet);

  const spaceValues = useMemo(
    () => ({
      padding: getStyleValue(padding || p, space),
      paddingHorizontal: getStyleValue(paddingHorizontal || px, space),
      paddingVertical: getStyleValue(paddingVertical || py, space),
      paddingTop: getStyleValue(paddingTop || pt, space),
      paddingBottom: getStyleValue(paddingBottom || pb, space),
      paddingLeft: getStyleValue(paddingLeft || pl, space),
      paddingRight: getStyleValue(paddingRight || pr, space),
      paddingEnd: getStyleValue(paddingEnd, space),
      paddingStart: getStyleValue(paddingStart, space),
      margin: getStyleValue(m || margin, space),
      marginHorizontal: getStyleValue(marginHorizontal || mx, space),
      marginVertical: getStyleValue(marginVertical || my, space),
      marginTop: getStyleValue(marginTop || mt, space),
      marginBottom: getStyleValue(marginBottom || mb, space),
      marginLeft: getStyleValue(marginLeft || ml, space),
      marginRight: getStyleValue(marginRight || mr, space),
      marginEnd: getStyleValue(marginEnd, space),
      marginStart: getStyleValue(marginStart, space),
      columnGap: getStyleValue(columnGap, space),
      gap: getStyleValue(gap, space),
      rowGap: getStyleValue(rowGap, space),
      height: getStyleValue(height || h, space),
      width: getStyleValue(width || w, space),
      maxHeight: getStyleValue(maxHeight, space),
      maxWidth: getStyleValue(maxWidth, space),
    }),
    [
      padding,
      p,
      paddingHorizontal,
      px,
      paddingVertical,
      py,
      paddingTop,
      pt,
      paddingBottom,
      pb,
      paddingLeft,
      pl,
      paddingRight,
      pr,
      paddingEnd,
      paddingStart,
      margin,
      m,
      marginHorizontal,
      mx,
      marginVertical,
      my,
      marginTop,
      mt,
      marginBottom,
      mb,
      marginLeft,
      ml,
      marginRight,
      mr,
      gap,
      rowGap,
      columnGap,
      marginEnd,
      marginStart,
      height,
      h,
      width,
      w,
      maxHeight,
      maxWidth,
    ]
  );

  const colorValues = useMemo(
    () => ({
      backgroundColor: getStyleValue(backgroundColor || bg || bgColor, colors),
      borderColor: getStyleValue(borderColor, colors),
      borderBottomColor: getStyleValue(borderBottomColor, colors),
      borderLeftColor: getStyleValue(borderLeftColor, colors),
      borderRightColor: getStyleValue(borderRightColor, colors),
      borderTopColor: getStyleValue(borderTopColor, colors),
      borderBlockColor: getStyleValue(borderBlockColor, colors),
      borderBlockEndColor: getStyleValue(borderBlockEndColor, colors),
      borderBlockStartColor: getStyleValue(borderBlockStartColor, colors),
      borderEndColor: getStyleValue(borderEndColor, colors),
      borderStartColor: getStyleValue(borderStartColor, colors),
      shadowColor: getStyleValue(shadowColor, colors),
    }),
    [
      backgroundColor,
      bg,
      bgColor,
      borderColor,
      borderBottomColor,
      borderLeftColor,
      borderRightColor,
      borderTopColor,
      borderBlockColor,
      borderBlockEndColor,
      borderBlockStartColor,
      borderEndColor,
      borderStartColor,
      shadowColor,
    ]
  );

  const radiusValues = useMemo(
    () => ({
      borderRadius: getStyleValue(borderRadius || rounded, radii),
      borderBottomEndRadius: getStyleValue(borderBottomEndRadius, radii),
      borderBottomLeftRadius: getStyleValue(borderBottomLeftRadius, radii),
      borderBottomRightRadius: getStyleValue(borderBottomRightRadius, radii),
      borderBottomStartRadius: getStyleValue(borderBottomStartRadius, radii),
      borderTopEndRadius: getStyleValue(borderTopEndRadius, radii),
      borderTopLeftRadius: getStyleValue(borderTopLeftRadius, radii),
      borderTopRightRadius: getStyleValue(borderTopRightRadius, radii),
      borderTopStartRadius: getStyleValue(borderTopStartRadius, radii),
      borderEndEndRadius: getStyleValue(borderEndEndRadius, radii),
      borderEndStartRadius: getStyleValue(borderEndStartRadius, radii),
      borderStartEndRadius: getStyleValue(borderStartEndRadius, radii),
      borderStartStartRadius: getStyleValue(borderStartStartRadius, radii),
    }),
    [
      borderRadius,
      rounded,
      borderBottomEndRadius,
      borderBottomLeftRadius,
      borderBottomRightRadius,
      borderBottomStartRadius,
      borderTopEndRadius,
      borderTopLeftRadius,
      borderTopRightRadius,
      borderTopStartRadius,
      borderEndEndRadius,
      borderEndStartRadius,
      borderStartEndRadius,
      borderStartStartRadius,
    ]
  );

  const borderValues = useMemo(
    () => ({
      borderBottomWidth: getStyleValue(borderBottomWidth, borderWidths),
      borderEndWidth: getStyleValue(borderEndWidth, borderWidths),
      borderLeftWidth: getStyleValue(borderLeftWidth, borderWidths),
      borderRightWidth: getStyleValue(borderRightWidth, borderWidths),
      borderStartWidth: getStyleValue(borderStartWidth, borderWidths),
      borderTopWidth: getStyleValue(borderTopWidth, borderWidths),
      borderWidth: getStyleValue(borderWidth, borderWidths),
    }),
    [
      borderBottomWidth,
      borderEndWidth,
      borderLeftWidth,
      borderRightWidth,
      borderStartWidth,
      borderTopWidth,
      borderWidth,
    ]
  );

  const opacityValue = useMemo(() => getStyleValue(opacity, themeOpacity), [opacity]);

  const boxStyles = useMemo(
    () =>
      styles.box({
        alignContent,
        alignItems,
        alignSelf,
        aspectRatio,
        bottom,
        display,
        end,
        flex,
        flexBasis,
        flexDirection,
        flexGrow,
        flexShrink,
        flexWrap,
        justifyContent,
        left,
        minHeight,
        minWidth,
        overflow,
        position,
        right,
        start,
        top,
        zIndex,
        direction,
        backfaceVisibility,
        borderCurve,
        borderStyle,
        elevation,
        pointerEvents,
        cursor,
        shadowOffset,
        shadowOpacity,
        shadowRadius,
        transform,
        transformOrigin,
        ...borderValues,
        ...colorValues,
        ...radiusValues,
        ...spaceValues,
        opacity: opacityValue,
      }),
    [
      alignContent,
      alignItems,
      alignSelf,
      aspectRatio,
      borderBottomWidth,
      borderEndWidth,
      borderLeftWidth,
      borderRightWidth,
      borderStartWidth,
      borderTopWidth,
      borderWidth,
      bottom,
      display,
      end,
      flex,
      flexBasis,
      flexDirection,
      rowGap,
      gap,
      columnGap,
      flexGrow,
      flexShrink,
      flexWrap,
      height,
      h,
      justifyContent,
      left,
      spaceValues.margin,
      spaceValues.marginBottom,
      marginEnd,
      marginHorizontal,
      mx,
      marginLeft,
      ml,
      marginRight,
      mr,
      marginStart,
      marginTop,
      mt,
      marginVertical,
      my,
      maxHeight,
      maxWidth,
      minHeight,
      minWidth,
      overflow,
      spaceValues.padding,
      paddingBottom,
      paddingEnd,
      paddingHorizontal,
      px,
      paddingLeft,
      pl,
      paddingRight,
      pr,
      paddingStart,
      paddingTop,
      pt,
      paddingVertical,
      py,
      position,
      right,
      start,
      top,
      width,
      w,
      zIndex,
      direction,
      backfaceVisibility,
      backgroundColor,
      bg,
      bgColor,
      borderBlockColor,
      borderBlockEndColor,
      borderBlockStartColor,
      borderBottomColor,
      borderBottomEndRadius,
      borderBottomLeftRadius,
      borderBottomRightRadius,
      borderBottomStartRadius,
      borderColor,
      borderCurve,
      borderEndColor,
      borderEndEndRadius,
      borderEndStartRadius,
      borderLeftColor,
      borderRadius,
      rounded,
      borderRightColor,
      borderStartColor,
      borderStartEndRadius,
      borderStartStartRadius,
      borderStyle,
      borderTopColor,
      borderTopEndRadius,
      borderTopLeftRadius,
      borderTopRightRadius,
      borderTopStartRadius,
      opacity,
      elevation,
      pointerEvents,
      cursor,
      shadowColor,
      shadowOffset,
      shadowOpacity,
      shadowRadius,
      transform,
      transformOrigin,
    ]
  );

  return <View {...props} style={[styles.box(boxStyles), style]} />;
};

const stylesheet = createStyleSheet(() => ({
  box: styles => ({ ...styles }),
}));

export default memo(Box);
