import React from 'react';
import { Switch } from './';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Switch,
  'https://www.figma.com/design/3RY3OvLA88yZksRjOfjQJm/UW-App-UI?node-id=9551-7352&t=fDsV1m42i8hVbZo3-4',
  {
    props: {
      value: figma.boolean('checked'),
      state: figma.enum('state', {
        default: 'default',
      }),
      size: figma.enum('size', {
        'medium - 32': 'medium',
        'small - 24': 'small',
      }),
      disabled: figma.boolean('disabled'),
    },
    example: props => <Switch {...props} />,
  }
);
